# Generated by Django 3.2 on 2021-04-25 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id_recipe', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=700)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id_employee', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('id_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_delivery.recipe')),
            ],
        ),
    ]
